- name: Setup Keycloak stack
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: [docker.io, docker-compose]
        state: present
        update_cache: true

    - name: Run PostgreSQL container
      docker_container:
        name: postgres
        image: postgres:14
        env:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_DB: keycloak
        ports:
          - "5432:5432"

    - name: Run Keycloak container
      docker_container:
        name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        command: ["start-dev"]
        env:
          DB_VENDOR: POSTGRES
          DB_ADDR: localhost
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_PASSWORD: keycloak
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - "8080:8080"
        links:
          - postgres

    - name: Run Nginx static site
      docker_container:
        name: nginx-site
        image: nginx:alpine
        volumes:
          - /home/{{ ansible_user }}/site:/usr/share/nginx/html:ro
        ports:
          - "80:80"
