name: Ansible Disassembly

on:
  workflow_dispatch:

jobs:
  disassemble-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible sshpass

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TF_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create Ansible inventory
      run: |
        echo "[web]" > inventory.ini
        echo "${{ secrets.VM_DOMAIN_NAME }} ansible_user=${{ secrets.VM_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_pass='${{ secrets.TF_VM_SSH_PRIVATE_KEY_PASSWORD }}'" >> inventory.ini

    - name: Run Ansible Disassembly Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
      run: ansible-playbook -i inventory.ini ansible/disassemble.yml
