name: Configure VM with Ansible

on:
  workflow_dispatch:

jobs:
  configure-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible sshpass

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TF_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Disable SSH host key checking
      run: |
        echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" >> ~/.ssh/config

    - name: Create Ansible inventory
      run: |
        echo "[web]" > inventory.ini
        echo "${{ secrets.VM_DOMAIN_NAME }} ansible_user=${{ secrets.VM_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
        cat inventory.ini

    - name: Run Ansible Playbook
      env:
        KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: ansible-playbook -i inventory.ini ansible/playbook.yml
